# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ucc_chess_pb2 as ucc__chess__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ucc_chess_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InferenceServiceStub:
    """═══════════════════════════════════════════
    服务定义
    ═══════════════════════════════════════════

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.BatchInfer = channel.unary_unary(
                '/ucc.InferenceService/BatchInfer',
                request_serializer=ucc__chess__pb2.InferenceRequest.SerializeToString,
                response_deserializer=ucc__chess__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.UpdateModel = channel.unary_unary(
                '/ucc.InferenceService/UpdateModel',
                request_serializer=ucc__chess__pb2.ModelWeights.SerializeToString,
                response_deserializer=ucc__chess__pb2.Empty.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/ucc.InferenceService/Ping',
                request_serializer=ucc__chess__pb2.Empty.SerializeToString,
                response_deserializer=ucc__chess__pb2.Empty.FromString,
                _registered_method=True)


class InferenceServiceServicer:
    """═══════════════════════════════════════════
    服务定义
    ═══════════════════════════════════════════

    """

    def BatchInfer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateModel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InferenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'BatchInfer': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchInfer,
                    request_deserializer=ucc__chess__pb2.InferenceRequest.FromString,
                    response_serializer=ucc__chess__pb2.InferenceResponse.SerializeToString,
            ),
            'UpdateModel': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateModel,
                    request_deserializer=ucc__chess__pb2.ModelWeights.FromString,
                    response_serializer=ucc__chess__pb2.Empty.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=ucc__chess__pb2.Empty.FromString,
                    response_serializer=ucc__chess__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ucc.InferenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ucc.InferenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InferenceService:
    """═══════════════════════════════════════════
    服务定义
    ═══════════════════════════════════════════

    """

    @staticmethod
    def BatchInfer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ucc.InferenceService/BatchInfer',
            ucc__chess__pb2.InferenceRequest.SerializeToString,
            ucc__chess__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ucc.InferenceService/UpdateModel',
            ucc__chess__pb2.ModelWeights.SerializeToString,
            ucc__chess__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ucc.InferenceService/Ping',
            ucc__chess__pb2.Empty.SerializeToString,
            ucc__chess__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TrainingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushSamples = channel.stream_unary(
                '/ucc.TrainingService/PushSamples',
                request_serializer=ucc__chess__pb2.TrainingSample.SerializeToString,
                response_deserializer=ucc__chess__pb2.Empty.FromString,
                _registered_method=True)
        self.PullWeights = channel.unary_unary(
                '/ucc.TrainingService/PullWeights',
                request_serializer=ucc__chess__pb2.Empty.SerializeToString,
                response_deserializer=ucc__chess__pb2.ModelWeights.FromString,
                _registered_method=True)


class TrainingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PushSamples(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PullWeights(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TrainingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushSamples': grpc.stream_unary_rpc_method_handler(
                    servicer.PushSamples,
                    request_deserializer=ucc__chess__pb2.TrainingSample.FromString,
                    response_serializer=ucc__chess__pb2.Empty.SerializeToString,
            ),
            'PullWeights': grpc.unary_unary_rpc_method_handler(
                    servicer.PullWeights,
                    request_deserializer=ucc__chess__pb2.Empty.FromString,
                    response_serializer=ucc__chess__pb2.ModelWeights.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ucc.TrainingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ucc.TrainingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TrainingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushSamples(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/ucc.TrainingService/PushSamples',
            ucc__chess__pb2.TrainingSample.SerializeToString,
            ucc__chess__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PullWeights(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ucc.TrainingService/PullWeights',
            ucc__chess__pb2.Empty.SerializeToString,
            ucc__chess__pb2.ModelWeights.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
